# Generated by Django 4.1.7 on 2023-03-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("livraria", "0004_livro_alter_autor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to="livraria.categoria",
            ),
            preserve_default=False,
        ),
    ]
