# Generated by Django 4.2 on 2023-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0006_livro_editora"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="livraria.autor"),
        ),
    ]
